### ISSUE TITLE
Site header requires Twig Tweak module

### ISSUE THREAD

**Issue by BrentWMiller** [skycatchfire/fire#1]
Site header requires the [Twig Tweak](https://www.drupal.org/project/twig_tweak) module to work. All pages will display a non-descriptive error otherwise.

`{{ drupal_menu('main') }}` Uses Twig Tweak.

```twig
<header class="site-header" role="banner" data-fire-component="site-header">
	<a href="/" class="site-header__logo" data-logo>Fire Theme</a>
	{{ drupal_menu('main') }}
</header>
```

Not sure if we just want to drop this piece, or leave it and just note it somewhere.

**Comment by 1forh** [comment]
How about this? https://github.com/skycatchfire/fire/pull/3

**Comment by BrentWMiller** [comment]
@1forh Works for me.
