### ISSUE TITLE
lozad fade in

### ISSUE THREAD

**Issue by 1forh** [skycatchfire/fire#42]
add:

```
el.onload = () => {
    el.classList.add('lozad--faded');
};
```

**Comment by BrentWMiller** [comment]
```js
// lazy loads elements with default selector: `.lozad`
  const observer = lozad('.lozad', {
    loaded: function(el) {
      el.onload = function() {
        el.classList.add('lozad--loaded')
      }
    },
  });
  observer.observe();
```

**Comment by wuebkers** [comment]
`// lazy loads elements with default selector: `.lozad`
  const observer = lozad('.lozad', {
    loaded: function(el) {
      el.classList.add('lozad--loaded');

      el.onload = function() {
        el.classList.add('lozad--loaded');
      };
    },
    rootMargin: '0% 0% 100%',
  });
  observer.observe();`
