### ISSUE TITLE
add `afterBehaviorHit` to `registerAllComponents()` method in component-record.js

### ISSUE THREAD

**Issue by 1forh** [skycatchfire/fire#88]
Can also add `Drupal.behaviors to main.js`

https://github.com/skycatchfire/gamberjohnson.com-v2/blob/master/themes/fire/assets/scripts/base/component-record.js#L51

https://github.com/skycatchfire/gamberjohnson.com-v2/blob/master/themes/fire/main.js#L33

**Comment by BrentWMiller** [comment]
https://github.com/skycatchfire/fire/pull/92
